### ISSUE TITLE
Array intersection 

### ISSUE THREAD

**Issue by nanhu45** [BabaMalik/Coinding-NInjas-Introduction-to-Python#3]
array intersection 
Why it is not done

**Comment by BabaMalik** [comment]
> array intersection
> Why it is not done

I did not get you issue in the array intersection problem.

**Comment by nanhu45** [comment]
Bro error is coming in your code

**Comment by nanhu45** [comment]
In coading ninja it is showing runtime error

**Comment by nanhu45** [comment]
![Uploading 16050123513703713858425690645042.jpg…]()

**Comment by nanhu45** [comment]
Thanx

**Comment by BabaMalik** [comment]
> Thanx

> Keep Follow me in github.
